import numpy as np

h = np.load("/lustre/orion/stf218/proj-shared/brave/score-MRI/samples/dnp/original/1c57_honly.mtz_0.npy")
m = np.load("/lustre/orion/stf218/proj-shared/brave/score-MRI/samples/dnp/original/1C57_minus.mtz_0.npy")
p = np.load("/lustre/orion/stf218/proj-shared/brave/score-MRI/samples/dnp/original/1C57_plus.mtz_0.npy")
s = (slice(40, 41, None), slice(11, 12, None), slice(60, 65, None))
print(np.allclose(h,m))
print(np.allclose(h,p))
print(h[s])
print(m[s])
print(p[s])
print("printing abs:")
print(np.abs(h[s]))
print(np.abs(m[s]))
print(np.abs(p[s]))
print("printing angles:")
print(np.angle(h[s]))
print(np.angle(m[s]))
print(np.angle(p[s]))